# Generated by Django 3.1.2 on 2021-12-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suitable_vegetarian', models.BooleanField(default=False)),
                ('suitable_celiac', models.BooleanField(default=False)),
                ('menu_type', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='menus')),
            ],
        ),
        migrations.CreateModel(
            name='MenuOnSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('stock', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='menus.menu')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
