# Generated by Django 3.1.2 on 2021-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20201011_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucomponent',
            name='image',
            field=models.ImageField(null=True, upload_to='menu_components'),
        ),
    ]
