# Generated by Django 3.1.2 on 2021-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menucomponent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='suitable_celiac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='suitable_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
