# Generated by Django 3.1.2 on 2021-01-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20210106_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucomponent',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='components',
            field=models.ManyToManyField(to='menus.MenuComponent'),
        ),
    ]
