# Generated by Django 3.1.2 on 2021-04-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('menus', '0006_menuonsale_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuonsale',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='menus.menu'),
        ),
        migrations.AlterField(
            model_name='menuonsale',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
